version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  run_tests:
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Test
          command: |
            ./node_modules/.bin/mocha --reporter spec 
workflows:
  node-tests:
    jobs:
      - node/test
