version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  run_tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm test
workflows:
  node-tests:
    jobs:
      - node/test